service: serverless-scrobbler

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

package:
  include:
    - scrobbler.js
    - node_modules/**
  exclude:
    - package.json
    - package-lock.json

functions:
  scrobble:
    handler: scrobbler.scrobble
    events:
      - http:
          method: post
          path: scrobble
          cors: true
    environment:
      DROP_INVALID_DURATIONS: false
      ENABLE_LOGGING: false
