service: serverless-scrobbler

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

package:
  patterns:
    - handler.js
    - src/**
    - node_modules/**

functions:
  scrobble:
    handler: handler.handler
    events:
      - http:
          method: post
          path: scrobble
          cors: true
    environment:
      DROP_INVALID_DURATIONS: false
      ENABLE_LOGGING: false
